"use client";
import Nav from "./components/nav/Nav";
import "./globals.css";
import { Inter } from "next/font/google";
import { QueryClient, QueryClientProvider } from "react-query";

const queryClient = new QueryClient();

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <QueryClientProvider client={queryClient}>
      <html lang="en">
        <head>
          <title>Control Stock</title>
        </head>
        <body className={inter.className}>
          <Nav />
          {children}
        </body>
      </html>
    </QueryClientProvider>
  );
}
